# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/morpho/C/vulkan_rogue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/morpho/C/vulkan_rogue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morpho/C/vulkan_rogue/CMakeFiles /home/morpho/C/vulkan_rogue//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morpho/C/vulkan_rogue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vulkan_rogue

# Build rule for target.
vulkan_rogue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vulkan_rogue
.PHONY : vulkan_rogue

# fast build rule for target.
vulkan_rogue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/build
.PHONY : vulkan_rogue/fast

extern/vma.o: extern/vma.cpp.o
.PHONY : extern/vma.o

# target to build an object file
extern/vma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/extern/vma.cpp.o
.PHONY : extern/vma.cpp.o

extern/vma.i: extern/vma.cpp.i
.PHONY : extern/vma.i

# target to preprocess a source file
extern/vma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/extern/vma.cpp.i
.PHONY : extern/vma.cpp.i

extern/vma.s: extern/vma.cpp.s
.PHONY : extern/vma.s

# target to generate assembly for a file
extern/vma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/extern/vma.cpp.s
.PHONY : extern/vma.cpp.s

src/action.o: src/action.c.o
.PHONY : src/action.o

# target to build an object file
src/action.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/action.c.o
.PHONY : src/action.c.o

src/action.i: src/action.c.i
.PHONY : src/action.i

# target to preprocess a source file
src/action.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/action.c.i
.PHONY : src/action.c.i

src/action.s: src/action.c.s
.PHONY : src/action.s

# target to generate assembly for a file
src/action.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/action.c.s
.PHONY : src/action.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/config.c.s
.PHONY : src/config.c.s

src/drawing.o: src/drawing.c.o
.PHONY : src/drawing.o

# target to build an object file
src/drawing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/drawing.c.o
.PHONY : src/drawing.c.o

src/drawing.i: src/drawing.c.i
.PHONY : src/drawing.i

# target to preprocess a source file
src/drawing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/drawing.c.i
.PHONY : src/drawing.c.i

src/drawing.s: src/drawing.c.s
.PHONY : src/drawing.s

# target to generate assembly for a file
src/drawing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/drawing.c.s
.PHONY : src/drawing.c.s

src/input.o: src/input.c.o
.PHONY : src/input.o

# target to build an object file
src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/input.c.o
.PHONY : src/input.c.o

src/input.i: src/input.c.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/input.c.i
.PHONY : src/input.c.i

src/input.s: src/input.c.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/input.c.s
.PHONY : src/input.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/main.c.s
.PHONY : src/main.c.s

src/textures.o: src/textures.c.o
.PHONY : src/textures.o

# target to build an object file
src/textures.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/textures.c.o
.PHONY : src/textures.c.o

src/textures.i: src/textures.c.i
.PHONY : src/textures.i

# target to preprocess a source file
src/textures.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/textures.c.i
.PHONY : src/textures.c.i

src/textures.s: src/textures.c.s
.PHONY : src/textures.s

# target to generate assembly for a file
src/textures.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/textures.c.s
.PHONY : src/textures.c.s

src/vulkan_meta.o: src/vulkan_meta.c.o
.PHONY : src/vulkan_meta.o

# target to build an object file
src/vulkan_meta.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_meta.c.o
.PHONY : src/vulkan_meta.c.o

src/vulkan_meta.i: src/vulkan_meta.c.i
.PHONY : src/vulkan_meta.i

# target to preprocess a source file
src/vulkan_meta.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_meta.c.i
.PHONY : src/vulkan_meta.c.i

src/vulkan_meta.s: src/vulkan_meta.c.s
.PHONY : src/vulkan_meta.s

# target to generate assembly for a file
src/vulkan_meta.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_meta.c.s
.PHONY : src/vulkan_meta.c.s

src/vulkan_public.o: src/vulkan_public.c.o
.PHONY : src/vulkan_public.o

# target to build an object file
src/vulkan_public.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_public.c.o
.PHONY : src/vulkan_public.c.o

src/vulkan_public.i: src/vulkan_public.c.i
.PHONY : src/vulkan_public.i

# target to preprocess a source file
src/vulkan_public.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_public.c.i
.PHONY : src/vulkan_public.c.i

src/vulkan_public.s: src/vulkan_public.c.s
.PHONY : src/vulkan_public.s

# target to generate assembly for a file
src/vulkan_public.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/vulkan_public.c.s
.PHONY : src/vulkan_public.c.s

src/world.o: src/world.c.o
.PHONY : src/world.o

# target to build an object file
src/world.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/world.c.o
.PHONY : src/world.c.o

src/world.i: src/world.c.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/world.c.i
.PHONY : src/world.c.i

src/world.s: src/world.c.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_rogue.dir/build.make CMakeFiles/vulkan_rogue.dir/src/world.c.s
.PHONY : src/world.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vulkan_rogue"
	@echo "... extern/vma.o"
	@echo "... extern/vma.i"
	@echo "... extern/vma.s"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/drawing.o"
	@echo "... src/drawing.i"
	@echo "... src/drawing.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/textures.o"
	@echo "... src/textures.i"
	@echo "... src/textures.s"
	@echo "... src/vulkan_meta.o"
	@echo "... src/vulkan_meta.i"
	@echo "... src/vulkan_meta.s"
	@echo "... src/vulkan_public.o"
	@echo "... src/vulkan_public.i"
	@echo "... src/vulkan_public.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

