* TODO

message buffer -> ring buffer
changing view of tileset < - >
changing tileset < - >

handling non8*8 tiles
FOV/Line of Sight
NPCs / enemies basic basic
png->bdf to redistribute some assets

* back buffer / cache
two rendering functions
gfxRenderCache() -> take GfxTileInstances*, render to backbuffer
gfxRenderFrame() -> take GfxTileInstances*, render ontop of backbuffer. Reset size to 0 every frame.
gfxPresentFrame()

* vulkan style
| Functions | gfxFunctionName |
| Types     | GfxType         |
| Variables | variable_name   |
make pos x, pos y, textures_index, glyph_code, fgColor, bgColor
a coherent order

* CPU budget
60fps input/resize polling target fps - 16ms frame time
a 14ms wait on VkAcquireImageKHR gives 12.5% cpu usage:
    (1 - (14 / 16)) = 0.125

-02 no validation layers 1.5% 

* API
model API after ANSI escape codes + Ncurses
ANSI     ESC[2J      erase entire screen
curses   refresh()   Tell the curses system to dump the contents on the screen. It checks the window and updates only the portion which has been changed.
mvwaddch()	Move the cursor to a given position and then print as by addch() but into the given window.
Current implementation is addch(x, y, fg, bg, texture_index, ch);
probably better this way;

* Procederal
Static worldmap, procederal local tiles

writing driven story
william burroughs cut up tecnique

* Art

| Machine        | Display in Tiles   | Tile Size |
| Gameboy Screen | 20*18              | 8*8       |
| MSX            | 32*24              | 8*8       |

Roguelike overworld map, use ascii chars to draw architecture
Ex

** ideas
timur novikov style landscapes for long distances, some towns
background of horizon can change for weather/time/biome
foreground is game area, could be follow cam or static cam.k
mayan glyphs in textmode appear as characters.



* Turn based
https://journal.stuffwithstuff.com/2014/07/15/a-turn-based-game-loop/

* world
entities as rooms, multi tile entities
fixed interesting world size
player can walk into the wilderness/void like fallout 4, random chance of enemies spawning near the player
Multiple Z Levels
   stairs ^
can see enemies on multiple Z levels, X@COM

* woodcutting, firestarting
trees
lighters
usable objects

* combat
not annoying, tedious
pokemon mysery dungeon
