/* Asset Loading Options */
#define COLOR_TEXTURE_INDEX 0
#define PALETTE_SIZE 16
#define ASCII_TEXTURE_INDEX 1
#define DRAW_TEXTURE_INDEX 2
#define ATLAS_WIDTH 32
/* TO REMOVE */

#define DRAW_BUFFER_COUNT 2;

#define cfg_format (VkFormat)VK_FORMAT_B8G8R8A8_SRGB

#define ASCII_SCREEN_WIDTH 32
#define ASCII_SCREEN_HEIGHT 24
#define ASCII_TILE_SIZE 8
#define ASCII_SCALE 2.0f
#define MAX_SAMPLERS 64

#define DEBUG_BUFFER 0
#define DEBUG_LAYERS 0
